### ISSUE TITLE
Fatal exception when launching DirectBoot sample app

### ISSUE THREAD

**Issue by visiray-zz** [googlesamples/android-DirectBoot#2]
I saw the fatal exception when launching DirectBoot sample app.

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.directboot/com.example.android.directboot.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

My proposed change is using @style/Theme.AppCompat instead of @style/AppTheme.
From:

``` Java
    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/AppTheme"
```

To:

``` Java
    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/Theme.AppCompat"
```

**Comment by thagikura** [comment]
Thanks for the report. Now it should be fixed.
