### ISSUE TITLE
Does not work on Motorola Nexus6

### ISSUE THREAD

**Issue by DirajHS** [googlesamples/android-DirectBoot#6]
I am seeing this FATAL exception after boot saying:

java.lang.RuntimeException: Unable to instantiate receiver com.example.android.directboot.BootBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.example.android.directboot.BootBroadcastReceiver" on path: DexPathList

**Comment by davidlevitsky** [comment]
Was this ever resolved? I am having the same issue on Nexus 5X. @DirajHS please let me know if you ever found the solution to this.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
